import type { Lead as DbLead } from "@prisma/client";
import { Lead } from "@/types/lead";

export const mapDbLeadToLead = (lead: DbLead): Lead => ({
  id: lead.id,
  firstName: lead.firstName,
  lastName: lead.lastName,
  fullName: lead.fullName,
  company: lead.company,
  email: lead.email,
  phone: lead.phone,
  city: lead.city,
  state: lead.state,
  zip: lead.zip,
  leadType: lead.leadType as Lead["leadType"],
  source: lead.source as Lead["source"],
  sourceDetail: lead.sourceDetail,
  amountSpent: lead.amountSpent,
  notes: lead.notes,
  distanceMinutes: lead.distanceMinutes,
  score: lead.score,
  conversionScore: lead.conversionScore,
  projectFitScore: lead.projectFitScore,
  estimatedProjectTier: lead.estimatedProjectTier as Lead["estimatedProjectTier"],
  priorityTier: lead.priorityTier as Lead["priorityTier"],
  status: lead.status as Lead["status"],
  doNotContact: lead.doNotContact,
  deployVerifyVerdict: (lead.deployVerifyVerdict as Lead["deployVerifyVerdict"]) ?? null,
  lastContactedAt: lead.lastContactedAt?.toISOString(),
  nextFollowUpAt: lead.nextFollowUpAt?.toISOString(),
  createdAt: lead.createdAt.toISOString(),
  updatedAt: lead.updatedAt.toISOString(),
  enrichmentStatus: lead.enrichmentStatus as Lead["enrichmentStatus"],
  locationConfidence: (lead.locationConfidence as Lead["locationConfidence"]) ?? undefined,
  addressConfidence: lead.addressConfidence ?? null,
  confidenceNotes: lead.confidenceNotes ?? "",
  importedFromCsv: lead.importedFromCsv,
  googlePlaceId: lead.googlePlaceId ?? null,
  websiteUri: lead.websiteUri ?? null,
  websiteHost: lead.websiteHost ?? null,
  outreachHistory: [],
  replyHistory: [],
  bookingHistory: []
});
